#reference:
#https://docs.docker.com/compose/gettingstarted/
#https://medium.com/better-programming/using-variables-in-docker-compose-265a604c2006

version: "3.8"
services: 
    grpc:
        build:
            context: .
            dockerfile: ./api/grpc/Dockerfile
        ports:
            - "9001:9001"
        environment:
            WAIT_HOSTS: db:3306
            WAIT_HOSTS_TIMEOUT: 300
            WAIT_SLEEP_INTERVAL: 5
            WAIT_HOST_CONNECT_TIMEOUT: 30
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_HOST: db:3306
            DB_NAME: ${MYSQL_DATABASE}
            OMDB_API_KEY: ${OMDB_API_KEY}
        depends_on: 
            - db
        command: 
            sh -c "./wait && ./main"
    http:
        build: 
            context: .
            dockerfile: ./api/json_rpc_http/Dockerfile
        ports:
            - "9002:9002"
        environment:
            WAIT_HOSTS: db:3306
            WAIT_HOSTS_TIMEOUT: 300
            WAIT_SLEEP_INTERVAL: 5
            WAIT_HOST_CONNECT_TIMEOUT: 30
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_HOST: db:3306
            DB_NAME: ${MYSQL_DATABASE}
            OMDB_API_KEY: ${OMDB_API_KEY}
        depends_on: 
            - db
        command: 
            sh -c "./wait && ./main"
    db:
        image: mysql:8
        restart: always
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        expose: 
            - "3306"
volumes: 
    my-db:

