// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MovieAPIClient is the client API for MovieAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieAPIClient interface {
	SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...grpc.CallOption) (*SearchMovieResponse, error)
	GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...grpc.CallOption) (*GetMovieDetailResponse, error)
}

type movieAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieAPIClient(cc grpc.ClientConnInterface) MovieAPIClient {
	return &movieAPIClient{cc}
}

func (c *movieAPIClient) SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...grpc.CallOption) (*SearchMovieResponse, error) {
	out := new(SearchMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.MovieAPI/SearchMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieAPIClient) GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...grpc.CallOption) (*GetMovieDetailResponse, error) {
	out := new(GetMovieDetailResponse)
	err := c.cc.Invoke(ctx, "/movie.MovieAPI/GetMovieDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieAPIServer is the server API for MovieAPI service.
// All implementations must embed UnimplementedMovieAPIServer
// for forward compatibility
type MovieAPIServer interface {
	SearchMovie(context.Context, *SearchMovieRequest) (*SearchMovieResponse, error)
	GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error)
	mustEmbedUnimplementedMovieAPIServer()
}

// UnimplementedMovieAPIServer must be embedded to have forward compatible implementations.
type UnimplementedMovieAPIServer struct {
}

func (UnimplementedMovieAPIServer) SearchMovie(context.Context, *SearchMovieRequest) (*SearchMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovie not implemented")
}
func (UnimplementedMovieAPIServer) GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieDetail not implemented")
}
func (UnimplementedMovieAPIServer) mustEmbedUnimplementedMovieAPIServer() {}

// UnsafeMovieAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieAPIServer will
// result in compilation errors.
type UnsafeMovieAPIServer interface {
	mustEmbedUnimplementedMovieAPIServer()
}

func RegisterMovieAPIServer(s grpc.ServiceRegistrar, srv MovieAPIServer) {
	s.RegisterService(&_MovieAPI_serviceDesc, srv)
}

func _MovieAPI_SearchMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieAPIServer).SearchMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.MovieAPI/SearchMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieAPIServer).SearchMovie(ctx, req.(*SearchMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieAPI_GetMovieDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieAPIServer).GetMovieDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.MovieAPI/GetMovieDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieAPIServer).GetMovieDetail(ctx, req.(*GetMovieDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "movie.MovieAPI",
	HandlerType: (*MovieAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovie",
			Handler:    _MovieAPI_SearchMovie_Handler,
		},
		{
			MethodName: "GetMovieDetail",
			Handler:    _MovieAPI_GetMovieDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
